PRAGMA foreign_keys = ON;
CREATE TABLE plans (id TEXT PRIMARY KEY, scope_type TEXT NOT NULL, monthly_sends INTEGER NOT NULL DEFAULT 10000, contacts INTEGER NOT NULL DEFAULT 10000, rate INTEGER NOT NULL DEFAULT 5, features_json TEXT NOT NULL DEFAULT '{}');
CREATE TABLE resellers (id TEXT PRIMARY KEY, name TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'ACTIVE', plan_id TEXT REFERENCES plans(id), mc_parent_handle TEXT, mc_parent_key_ref TEXT, tracking_pattern TEXT, webhook_url TEXT, webhook_secret_ref TEXT, oidc_json TEXT, sso_secret_ref TEXT, system_email_from TEXT, system_email_key_ref TEXT, created_at TEXT NOT NULL);
CREATE TABLE accounts (id TEXT PRIMARY KEY, reseller_id TEXT NOT NULL REFERENCES resellers(id), name TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'PROVISIONING', plan_id TEXT REFERENCES plans(id), mc_handle TEXT UNIQUE, mc_key_ref TEXT, jurisdiction TEXT NOT NULL DEFAULT 'default', postal_address TEXT NOT NULL DEFAULT '', retention_days INTEGER NOT NULL DEFAULT 90, last_alarm_at TEXT, last_metered_at TEXT, provider_usage_json TEXT, abuse_breaches INTEGER NOT NULL DEFAULT 0, created_at TEXT NOT NULL);
CREATE INDEX accounts_reseller ON accounts(reseller_id, id);
CREATE TABLE users (id TEXT PRIMARY KEY, email TEXT NOT NULL UNIQUE COLLATE NOCASE, name TEXT NOT NULL DEFAULT '', email_verified_at TEXT, status TEXT NOT NULL DEFAULT 'ACTIVE', created_at TEXT NOT NULL);
CREATE TABLE role_assignments (user_id TEXT NOT NULL REFERENCES users(id), scope_type TEXT NOT NULL CHECK(scope_type IN ('platform','reseller','account')), scope_id TEXT NOT NULL, role TEXT NOT NULL, PRIMARY KEY(user_id,scope_type,scope_id));
CREATE TABLE sessions (id TEXT PRIMARY KEY, user_id TEXT NOT NULL REFERENCES users(id), hostname TEXT NOT NULL, actor_user_id TEXT, scope_type TEXT NOT NULL, scope_id TEXT NOT NULL, expires_at INTEGER NOT NULL, reason TEXT, created_at TEXT NOT NULL);
CREATE INDEX sessions_user ON sessions(user_id);
CREATE TABLE login_tokens (token_hash TEXT PRIMARY KEY, user_id TEXT NOT NULL REFERENCES users(id), hostname TEXT NOT NULL, scope_type TEXT NOT NULL, scope_id TEXT NOT NULL, expires_at INTEGER NOT NULL, used_at INTEGER);
CREATE TABLE hostnames (hostname TEXT PRIMARY KEY, reseller_id TEXT REFERENCES resellers(id), cf_custom_hostname_id TEXT, status TEXT NOT NULL DEFAULT 'PENDING', verification_json TEXT, verified_at TEXT);
CREATE TABLE themes (reseller_id TEXT PRIMARY KEY REFERENCES resellers(id), tokens_json TEXT NOT NULL DEFAULT '{}', css_object_key TEXT, logo_object_key TEXT, favicon_object_key TEXT, version INTEGER NOT NULL DEFAULT 1);
CREATE TABLE secrets (id TEXT PRIMARY KEY, ciphertext TEXT NOT NULL, created_at TEXT NOT NULL);
CREATE TABLE sender_domains (id TEXT PRIMARY KEY, account_id TEXT NOT NULL REFERENCES accounts(id), domain TEXT NOT NULL, dkim_selector TEXT, dkim_key_ref TEXT, records_json TEXT NOT NULL DEFAULT '[]', lockdown_ok INTEGER NOT NULL DEFAULT 0, dkim_ok INTEGER NOT NULL DEFAULT 0, spf_ok INTEGER NOT NULL DEFAULT 0, verified_at TEXT, UNIQUE(account_id,domain));
CREATE TABLE tracking_domains (id TEXT PRIMARY KEY, account_id TEXT NOT NULL REFERENCES accounts(id), name TEXT NOT NULL, hostname TEXT NOT NULL, scope TEXT NOT NULL, verify_token TEXT, status TEXT NOT NULL DEFAULT 'PENDING', next_attempt INTEGER NOT NULL DEFAULT 0, UNIQUE(account_id,scope));
CREATE TABLE api_keys (id TEXT PRIMARY KEY, reseller_id TEXT NOT NULL REFERENCES resellers(id), key_hash TEXT NOT NULL UNIQUE, scopes TEXT NOT NULL, last_used_at TEXT, revoked_at TEXT, created_at TEXT NOT NULL);
CREATE TABLE usage_daily (scope_type TEXT NOT NULL, scope_id TEXT NOT NULL, day TEXT NOT NULL, accepted INTEGER NOT NULL DEFAULT 0, delivered INTEGER NOT NULL DEFAULT 0, bounced INTEGER NOT NULL DEFAULT 0, complained INTEGER NOT NULL DEFAULT 0, provider_accepted INTEGER NOT NULL DEFAULT 0, PRIMARY KEY(scope_type,scope_id,day));
CREATE TABLE audit_log (id TEXT PRIMARY KEY, at TEXT NOT NULL, actor_user_id TEXT NOT NULL, impersonating TEXT, scope_type TEXT NOT NULL, scope_id TEXT NOT NULL, action TEXT NOT NULL, target TEXT NOT NULL, detail_json TEXT NOT NULL DEFAULT '{}');
CREATE INDEX audit_scope ON audit_log(scope_type,scope_id,at);
CREATE TABLE provisioning (account_id TEXT PRIMARY KEY REFERENCES accounts(id), idempotency_key TEXT NOT NULL, step TEXT NOT NULL DEFAULT 'CREATE', attempts INTEGER NOT NULL DEFAULT 0, error TEXT, next_attempt INTEGER NOT NULL DEFAULT 0, UNIQUE(idempotency_key));
CREATE TABLE alerts (id TEXT PRIMARY KEY, account_id TEXT, kind TEXT NOT NULL, detail_json TEXT NOT NULL, created_at TEXT NOT NULL, resolved_at TEXT);
CREATE TABLE dead_letters (id TEXT PRIMARY KEY, account_id TEXT, queue TEXT NOT NULL, body_json TEXT NOT NULL, error TEXT, created_at TEXT NOT NULL, replayed_at TEXT);
CREATE TABLE outbound_events (id TEXT PRIMARY KEY, reseller_id TEXT NOT NULL REFERENCES resellers(id), type TEXT NOT NULL, payload_json TEXT NOT NULL, attempts INTEGER NOT NULL DEFAULT 0, next_attempt INTEGER NOT NULL DEFAULT 0, delivered_at TEXT);
CREATE TABLE sso_nonces (nonce TEXT PRIMARY KEY, expires_at INTEGER NOT NULL);
CREATE TABLE system_emails (id TEXT PRIMARY KEY, reseller_id TEXT, recipient TEXT NOT NULL, subject TEXT NOT NULL, body TEXT NOT NULL, created_at TEXT NOT NULL, sent_at TEXT, attempts INTEGER NOT NULL DEFAULT 0);
CREATE TABLE auth_throttle (key TEXT PRIMARY KEY, count INTEGER NOT NULL, window INTEGER NOT NULL);
CREATE TABLE oidc_states (state_hash TEXT PRIMARY KEY, hostname TEXT NOT NULL, reseller_id TEXT NOT NULL, verifier TEXT NOT NULL, nonce TEXT NOT NULL, expires_at INTEGER NOT NULL);

INSERT INTO plans(id,scope_type,monthly_sends,contacts,rate) VALUES ('starter','account',10000,10000,5),('reseller','reseller',100000,100000,50);
